OnlineCommerce_WEB/OnlineCommerce_WEB/Controllers/CustomerController.cs
using OnlineCommerce_WEB.Models;
using OnlineCommerce_WEB.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineCommerce_WEB.Controllers
{
    public class CustomerController : Controller
    {
        OnlineCommerceEntities db = new OnlineCommerceEntities();

        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        // GET: Customer/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customer/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Customer/Edit/5
        public ActionResult Edit()
        {
            return View();
        }

        // POST: Customer/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Customers entity)
        {
            try
            {
                var customer = (from c in db.Customers where c.AccountID == CurrentLoginEntity.ID select c).FirstOrDefault();
                if (customer == null)
                {
                    Customers c = new Customers();
                    c.Name = entity.Name;
                    c.Surname = entity.Surname;
                    c.Phone = entity.Phone;
                    c.Mail = entity.Mail;
                    c.Address = entity.Address;
                    c.AccountID = CurrentLoginEntity.ID;
                    CurrentLoginEntity.Name = entity.Name;

                    db.Customers.Add(c);
                }
                else
                {
                    customer.Name = entity.Name;
                    customer.Surname = entity.Surname;
                    customer.Phone = entity.Phone;
                    customer.Mail = entity.Mail;
                    customer.Address = entity.Address;
                    customer.AccountID = CurrentLoginEntity.ID;
                    CurrentLoginEntity.Name = customer.Name;
                }


                
                db.SaveChanges();


                return RedirectToAction("Index");
            }
            catch
            {
                db.Entry(entity).State = EntityState.Modified;
                db.SaveChanges();

                return View();
            }
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Customer/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

OnlineCommerce_WEB/OnlineCommerce_WEB/Controllers/LoginController.cs
using OnlineCommerce_WEB.Models;
using OnlineCommerce_WEB.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineCommerce_WEB.Controllers
{
    public class LoginController : Controller
    {
        private OnlineCommerceEntities db = new OnlineCommerceEntities();
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(LoginEntity entity)
        {
            var user = (from u in db.Accounts
                        where u.Username == entity.Username
                        select u).Any();

            if (user) // Kullanıcı adı varmı kontrolü
            {
                var pass = db.Accounts.Where(p => p.Username == entity.Username).FirstOrDefault<Accounts>();

                Encryption enc = new Encryption();

                if (pass.Password == entity.Password || enc.Decrypt(pass.Password) == entity.Password) // Veri tabanındaki şifrelenmiş şifre ile aynı mı kontrolü
                {
                    Response.Write("<script>alert('Giriş Başarılı')</script>");
                    entity.IsLogin = true;

                    // Giriş yapan kullanıcnın bilgilerini alıyoruz.
                    CurrentLoginEntity.ID = (from u in db.Accounts
                                             where u.Username == entity.Username
                                             select u.ID).FirstOrDefault();
                    CurrentLoginEntity.IsLogin = true;
                    CurrentLoginEntity.Username = entity.Username;
                    CurrentLoginEntity.Password = entity.Password;

                    try // Giriş yapan kullanıcı bilgilerini dolduruyoruz
                    {
                        var en = (from e in db.Customers where e.AccountID == CurrentLoginEntity.ID select e).FirstOrDefault();
                        if (en != null)
                        {
                            CurrentLoginEntity.Name = en.Name;
                        }
                        else
                        {
                            Console.WriteLine("Kullanıcının adı yok");
                        }
                    }
                    catch(Exception e)
                    {
                        Console.WriteLine("Beklenmeyen bir hata oluştu.." + e.Message);
                    }
                    

                    return Redirect("/Products");// Giriş yaptıktan sonra ürünler sayfasına yönlendiriyor

                }
                else
                {
                    Response.Write("<script>alert('Şifre Hatalı')</script>");
                    entity.IsLogin = false;
                }
            }
            else
            {
                Response.Write("<script>alert('Başka bir kullanıcı adı giriniz.')</script>"); // Hata Mesajı
                entity.IsLogin = false;
            }
            return View();
        }

        public RedirectResult Logout()
        {
            CurrentLoginEntity.IsLogin = false;
            CurrentLoginEntity.Name = null;
            return Redirect("/Home"); // Çıkış yaptıktan sonra ana sayfaya yönlendiriyor.
        }
    }
}

OnlineCommerce_WEB/OnlineCommerce_WEB/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineCommerce_WEB.Models;
using OnlineCommerce_WEB.Models.EntityFramework;

namespace OnlineCommerce_WEB.Controllers
{
    public class OrdersController : Controller
    {
        OnlineCommerceEntities db = new OnlineCommerceEntities();

        List<ShoppingCart> shoppingList = new List<ShoppingCart>();
        // GET: Orders
        public ActionResult Index()
        {
            TempData.Keep(); // Sepetteki ürünler kaybolmasın diye
            return View();
        }

        
        [HttpPost]
        public ActionResult AddToCart(int productID, FormCollection formCollection)
        {
            Products prod = db.Products.Where(x => x.ID == productID).SingleOrDefault();

            var productAmount = formCollection["Amount"];

            ShoppingCart cart = new ShoppingCart();
            cart.productID = prod.ID;
            cart.productName = prod.Name;
            cart.price = (float)prod.Price;
            cart.amount = int.Parse(productAmount);
            cart.bill = cart.price * cart.amount;


            if (TempData["shoppingList"]==null)
            {
                shoppingList.Add(cart);
                TempData["shoppingList"] = shoppingList;
                
            }
            else
            {
                List<ShoppingCart> tempShoppingList = TempData["shoppingList"] as List<ShoppingCart>;
                tempShoppingList.Add(cart);
                TempData["shoppingList"] = tempShoppingList;
            }


            if (TempData["shoppingList"]!=null) // Sepetteki toplam ürün fiyatı için
            {
                float totalBill = 0;
                List<ShoppingCart> tempShoppingList = TempData["shoppingList"] as List<ShoppingCart>;
                foreach (var item in tempShoppingList)
                {
                    totalBill += item.bill;
                }
                TempData["TotalBill"] = totalBill;
            }

            
            TempData.Keep();

            GlobalVariables.CartProductCount += 1;

            return Redirect("/Products");
        }

        public ActionResult ShoppingCart()
        {
            TempData.Keep(); // Sepetteki ürünler kaybolmasın diye
            return View();
        }

        public ActionResult DeleteFromCart(int id)
        {
            var shoppingList = TempData["shoppingList"] as List<ShoppingCart>;
            shoppingList = shoppingList.Where(cart => cart.productID != id).ToList();

            var item = shoppingList.Where(cart => cart.productID == id).SingleOrDefault();

            TempData["TotalBill"] = shoppingList.Sum(c => c.bill);

            TempData["shoppingList"] = shoppingList;

            GlobalVariables.CartProductCount -= 1;

            return Redirect("/Orders/ShoppingCart");

        }
    }
}

OnlineCommerce_WEB/OnlineCommerce_WEB/Views/Shared/_Layout.cshtml
@using OnlineCommerce_WEB.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Online Commerce</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/Footer.css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Online Commerce", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Products", "Index", "Products")</li>
                    @*<li>@Html.ActionLink("Accounts", "Index", "Accounts")</li>*@
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @if (CurrentLoginEntity.IsLogin)
                {
                    <ul class="nav navbar-nav navbar-right">

                        <li>
                            <a href="/Orders/ShoppingCart" class="non-padding">
                                <svg class="bi bi-cart-check-fill" viewBox="-7 -5 30 20" xmlns="http://www.w3.org/2000/svg">
                                    <text>@Html.ActionLink("" + GlobalVariables.CartProductCount, "ShoppingCart", "Orders")</text>
                                    <path fill-rule="evenodd" d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zM4 14a1 1 0 1 1 2 0 1 1 0 0 1-2 0zm7 0a1 1 0 1 1 2 0 1 1 0 0 1-2 0zm.354-7.646a.5.5 0 0 0-.708-.708L8 8.293 6.854 7.146a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z" />
                                </svg>
                            </a>
                        </li>
                        @if (CurrentLoginEntity.Name != null)
                        {
                            <li> @Html.ActionLink("Hello \t" + CurrentLoginEntity.Name, "Index", "Customer") </li>
                        }
                        else
                        {
                            <li> @Html.ActionLink("Hello \t" + CurrentLoginEntity.Username, "Index", "Customer") </li>
                        }

                        <li> @Html.ActionLink("Log Out", "Logout", "Login") </li> @* Log out yapacak*@
                    </ul>
                }
                @if (CurrentLoginEntity.IsLogin == false)
                {
                    @Html.Partial("_LoginPartial")
                }


            </div>
        </div>
    </div>
    <div class="render-body">
        @RenderBody()
    </div>


    @* Footer Başlangıç *@
    <div>
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-xs-12 about-company">
                        <h2>Online Commerce</h2>
                        <p class="pr-5 text-white-50">New center of online commerce! </p>
                        <p><a href="#"><i class="fa fa-facebook-square mr-1"></i></a><a href="#"><i class="fa fa-linkedin-square"></i></a></p>
                    </div>
                    <div class="col-lg-3 col-xs-12 links">
                        <h4 class="mt-lg-0 mt-sm-3">Links</h4>
                        <ul class="m-0 p-0">
                            <li>- <a href="/Home">Home</a></li>
                            <li>- <a href="/Products">Products</a></li>
                            <li>- <a href="/Home/About">About</a></li>
                            <li>- <a href="/Home/Contact">Contact</a></li>
                            <li>- <a href="/Accounts/Create">Register</a></li>
                            <li>- <a href="/Login">Login</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-4 col-xs-12 location">
                        <h4 class="mt-lg-0 mt-sm-4">Location</h4>
                        <p>Turgutlu / Manisa / Turkey</p>
                        <p class="mb-0"><i class="fa fa-phone mr-3"></i>+905000000000</p>
                        <p><i class="fa fa-envelope-o mr-3"></i>onlinecommerce@cbu.edu.tr</p>
                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col copyright">
                        <p class=""><small class="text-white-50">© 2020. All Rights Reserved. Online Commerce</small></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @* Footer Sonu *@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>